os: linux
language: generic
sudo: required
git:
  depth: 3
services: postgresql
before_install:
- eval "$(curl -sL https://apt.vapor.sh)"; sudo apt-get update; sudo apt-get install
  swift vapor
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- git clone https://github.com/realm/SwiftLint.git && cd SwiftLint && swift build
  -c release --static-swift-stdlib && sudo mv .build/x86_64-unknown-linux/release/swiftlint
  /usr/local/bin && cd ..
script:
- swiftlint
- swift build && swift test
deploy:
  provider: heroku
  api_key:
    secure: u8MbyXG+ii14vZrRlPqaXnIGL+4p1AUTrnx+kGmQZG/5D1EJQgr7m37X2m3p+6GPc0oACpXUWdZiHICajv91SVKmQVtyCTvvNbNntb6lTsRHSlzmnPUFH3Aym6BaLE7QO89zPvuEMDITtgI5EHtEb0POX1xQ1MZjNXLPOT2HlrHAzUcAkdhILV8KE0bkB7zyoIC3BKCkocHqbIkTo2QKvE/Dg+VqcH5KPc77rTmNylj3dPrT/rTcquAdg0TjaOb769lP7TSeO6pmFJXxZdLhwXmrboEiK1Gg7DE1Vo8nrzEnXjxXQ5VYu2yzm2u3QMhbd6RoF3X9e2P9g3K0VXX8EM3AamzJ8gTVMYXJ+BNvInf+00ysT7H0DqJC2rcrclrgTjB1zjHZJsCFblUpUaVQ1UNM/P23EtgukIfdjoTOyz02v9e0evrnJsSTWKTPqShi+bpgoWrftCPnAGC5OAjlLPv0/gQGNIDP8t3KbgmOjyvgy2See6FIEZLnH3bI75AIE+lgmOjYVgESv7ppDl1wjh3IotJGjIcQp8ePftsu0g2xsZFWELdgD13UwhIMCz4IqK8k23cqbZPL37Ky9DrMtFTvkO/UmuzvZ/K4YPQBrxw0Sc+XxpvZBelg97bghELQfZzMBn/9rdRrvoy6rUORaEWZPkpYvMMzYlULa22kFD0=
